language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - deps=high

matrix:
    include:
        - php: hhvm
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=low

install:
    - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest update; fi;
    - if [ "$deps" != "low" ]; then composer --prefer-source update; fi;

script:
    - make test
